#!/usr/bin/env bash
# export-gemini.sh — the Gemini CLI extension dialect, from the Claude sources.
#
# Sourced by tools/export.sh, never executed. One function per output, each
# writing to $XOUT. The canonical sources stay agents/, commands/, skills/ and
# rules/; nothing here edits them.
#
# What is generated, and why each is generated at all:
#   gemini-extension.json  the one manifest a Gemini extension has. Nothing in
#                          the Claude layout is read natively, so the manifest,
#                          the context file, the commands, the skills and the
#                          hooks all have to exist here.
#   DEVIL.md               the 12 always-on rules, as the manifest's
#                          contextFileName. Named DEVIL.md, not GEMINI.md, so
#                          the host's own memory file is never shadowed.
#   commands/<n>.toml      description plus body, $ARGUMENTS rewritten to the
#                          {{args}} placeholder, /devil:<n> to the /<n> Gemini
#                          registers.
#   skills/<n>/SKILL.md    copied verbatim, which the loader allows: it reads
#                          name and description and ignores every other key.
#   agents/<n>.md          name, description, kind and a tools list. The agent
#                          schema is strict, so `model:` and `memory:` are
#                          dropped rather than carried and rejected.
#   hooks/                 hooks.json in Gemini's event names, plus a copy of
#                          the kit's own hook runtime and a one-file translator
#                          in front of it.
#   README.md              the install contract and the honest capability table.
#
# Not generated: templates/mcp.json (a host declares its own `mcpServers`),
# `tools/`, so the session briefing has nothing to run and is a documented
# degradation rather than a copy of the kit's scripts.

# --- primitives -------------------------------------------------------------

# Every generated file opens with a line its own format can carry as a comment.
# A frontmatter file cannot START with it: line 1 has to be the `---` fence, so
# those carry it on line 2 inside the block, which YAML reads as a comment.
GM_NOTICE="GENERATED by 'devil export gemini' from the kit's Claude-format sources. Do not edit; run 'devil export gemini' instead."
GM_MD="<!-- $GM_NOTICE -->"
GM_YAML="# $GM_NOTICE"
GM_TOML="$GM_YAML"

# The interpreter and the script in ONE string: Gemini's hook has no `args`
# array, so anything else here becomes a command naming only its interpreter.
GEMINI_HOOK_CMD='python3 ${extensionPath}/hooks/gemini-hook.py'

gemit() {
  mkdir -p "$(dirname "$XOUT/$1")"
  cat >"$XOUT/$1"
}

grule_names() { find "$(claude_root)/rules" -maxdepth 1 -name '*.md' -printf '%f\n' | sort; }

# A top-level string field of a JSON file, jq when installed else sed.
# Caveat: the sed read matches the first `"key": "..."` on a line anywhere in
# the file, so a nested or commented one is read as the top-level value, and a
# value broken across lines is not matched at all (it then reads as empty).
gjson_str() {
  if have jq; then
    jq -r --arg k "$2" '.[$k] // empty' "$1" 2>/dev/null
  else
    sed -nE "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"([^\"]*)\".*/\1/p" "$1" | head -1
  fi
}

# --- the manifest -----------------------------------------------------------

# One version source: plugin.json carries it, and this file reads it at export
# time rather than keeping a copy. A version bump therefore needs the export
# re-run, which is the same bargain every generated manifest makes.
# Caveat: the description's harness name is a literal substitution, not a
# template. It rewrites "Claude Code" and nothing else, so a reworded sentence
# carrying a different harness name would be emitted unchanged and wrong.
gmanifest() {
  local root version desc
  root="$(claude_root)"
  version="$(gjson_str "$root/.claude-plugin/plugin.json" version)"
  desc="$(gjson_str "$root/.claude-plugin/plugin.json" description)"
  desc="${desc//Claude Code/Gemini CLI}"
  {
    printf '{\n'
    printf '  "_comment": "%s",\n' "$GM_NOTICE"
    printf '  "name": "devil",\n'
    printf '  "version": "%s",\n' "$version"
    printf '  "description": "%s",\n' "$desc"
    printf '  "contextFileName": "DEVIL.md"\n'
    printf '}\n'
  } | gemit "gemini-extension.json"
}

# --- the always-on rules ----------------------------------------------------

gcontext() {
  local root f
  root="$(claude_root)"
  {
    printf '%s\n' "$GM_MD"
    printf '\n# Always-on rules\n\nThe kit, generated. Every file below is a verbatim\n'
    printf 'copy of `rules/<name>.md` in the kit; edit those, then re-export.\n'
    for f in "$root"/rules/*.md; do
      printf '\n---\n\n'
      cat "$f"
    done
  } | gemit "DEVIL.md"
}

# --- commands ---------------------------------------------------------------

# TOML has no comment form for a value and no interpolation, so the body is
# written as a multi-line basic string. Backslash first, then the quote, or the
# escaping would be escaped again.
gtoml_escape() { sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

# Gemini's placeholder is {{args}} and its registered name has no namespace, so
# keeping /devil:<name> would name a command that does not exist.
gdial() { sed -E -e "s#/devil:$1\b#/$1#g" -e 's/\$ARGUMENTS/{{args}}/g' -e 's/\$1/{{args}}/g'; }

gcommand() {
  local f="$1" name desc
  name="$(fm_field "$f" name)"
  [ -n "$name" ] || name="$(basename "$f" .md)"
  desc="$(fm_desc "$f" | gdial "$name" | tr '\n' ' ' | sed 's/[[:space:]]*$//' | gtoml_escape)"
  {
    printf '%s\n' "$GM_TOML"
    printf 'description = "%s"\n' "$desc"
    printf 'prompt = """\n'
    # The blank line after the closing fence is not part of the body, and a
    # prompt that opens with one reads as a stray empty paragraph.
    fm_body "$f" | sed '1{/^[[:space:]]*$/d}' | gdial "$name" | gtoml_escape
    printf '"""\n'
  } | gemit "commands/$name.toml"
}

gcommands() {
  local f
  for f in "$(claude_root)"/commands/*.md; do
    [ -e "$f" ] || continue
    gcommand "$f"
  done
}

# --- skills -----------------------------------------------------------------

# The notice goes INSIDE the fence, on line 2, for two reasons that point the same
# way. The loader parses the first `---` block, so a comment there is a YAML
# comment and costs nothing. A comment BELOW the closing fence is body text, and
# `# GENERATED` in body text is an H1: every copied skill would gain a second
# top-level heading and a trailing full stop, and markdownlint is right to say so.
gskill() {
  local f="$1" name
  name="$(basename "$(dirname "$f")")"
  awk -v notice="$GM_YAML" 'NR == 2 { print notice } { print }' "$f" |
    gemit "skills/$name/SKILL.md"
}

gskills() {
  local f
  for f in "$(claude_root)"/skills/*/SKILL.md; do
    [ -e "$f" ] || continue
    gskill "$f"
  done
}

# --- agents -----------------------------------------------------------------

# Claude tool name -> the Gemini tool that governs it. The list is the reverse
# of the mapping `gemini hooks migrate` applies, so it is the CLI's own answer
# to the same question. `model:` is dropped on purpose: the brief forbids model
# identifiers in a generated file, and the right provider is the host's choice.
gtool() {
  case "$1" in
  Read) echo read_file ;;
  Grep) echo grep ;;
  Glob) echo glob ;;
  LS) echo ls ;;
  Edit | MultiEdit | NotebookEdit | Patch) echo replace ;;
  Write) echo write_file ;;
  Bash | BashOutput | KillShell) echo run_shell_command ;;
  WebFetch) echo web_fetch ;;
  WebSearch) echo google_web_search ;;
  Skill) echo activate_skill ;;
  *) echo "" ;;
  esac
}

# A Gemini subagent's `tools` is an allow list and an omitted one INHERITS every
# tool, so an agent with no recognisable grant must still be given the empty
# list. An empty array is truthy in JS, which is why it means no tools and not
# all of them; an omitted `tools:` key would be the dangerous reading.
gagent() {
  local f="$1" name desc tool mapped
  name="$(fm_field "$f" name)"
  desc="$(fm_desc "$f")"
  mapped=""
  while read -r tool; do
    [ -n "$(gtool "$tool")" ] || continue
    mapped="$mapped$(gtool "$tool")
"
  done < <(claude_tools "$f" | sort -u)
  {
    echo "---"
    echo "$GM_YAML"
    # name and description are both required by the agent schema, and the name
    # is the tool name the main agent calls.
    printf 'name: %s\n' "$name"
    printf 'description: >\n'
    printf '%s\n' "$desc" | fold -s -w 88 | sed 's/[[:space:]]*$//; s/^/  /'
    echo "kind: local"
    if [ -z "$mapped" ]; then
      echo "tools: []"
    else
      echo "tools:"
      printf '%s' "$mapped" | sed 's/^/  - /'
    fi
    echo "---"
  } | gemit "agents/$name.md"
  # The body is appended as it is. An extra `printf '\n'` after a body that
  # already ends in a newline is what put MD012 in the OpenCode export.
  fm_body "$f" >>"$XOUT/agents/$name.md"
}

gagents() {
  local f
  for f in "$(claude_root)"/agents/*.md; do
    [ -e "$f" ] || continue
    gagent "$f"
  done
}

# --- hooks ------------------------------------------------------------------

# One hook definition, emitted four times: <event> <name> <timeout> [matcher].
# The times are the kit's budgets restated, not copied: Gemini reads milliseconds
# where the Claude manifest means seconds, so a copied 5 would be 5 ms.
gevent() {
  local event="$1" name="$2" ms="$3" matcher="$4" m=''
  [ -n "$matcher" ] && m="\"matcher\": \"$matcher\", "
  printf '    "%s": [ { %s"hooks": [ { "name": "%s", "type": "command", "command": "%s", "timeout": %s } ] } ]%s\n' \
    "$event" "$m" "$name" "$GEMINI_HOOK_CMD" "$ms" "$5"
}

# The four events the kit enforces, in Gemini's names, through the one file that
# speaks both dialects. `command` is a shell string here and has no `args` array.
ghooks() {
  local matcher='run_shell_command|write_file|replace|read_file|read_many_files|glob|grep|ls'
  {
    printf '{\n'
    printf '  "description": "%s",\n' "$GM_NOTICE"
    printf '  "hooks": {\n'
    gevent BeforeTool devil-risk 5000 "$matcher" ,
    gevent AfterTool devil-gate 5000 "$matcher" ,
    gevent SessionStart devil-briefing 10000 "" ,
    gevent PreCompress devil-compact 10000 "" ""
    printf '  }\n'
    printf '}\n'
  } | gemit "hooks/hooks.json"
  {
    printf '%s\n' "$GM_YAML"
    cat "$(claude_root)/tools/lib/gemini-hook.py"
  } | gemit "hooks/gemini-hook.py"
  # The runtime travels as a copy with a notice comment on line 1, which is
  # above the module docstring and still leaves it a docstring: a comment is not
  # a statement, so `__doc__` is unchanged. hooks/config/hooks-config.json is
  # copied byte for byte instead, because kit.py merges it into the switch set
  # and a key added here would be a key the switch set never declared.
  local f
  for f in "$(claude_root)"/hooks/scripts/*.py "$(claude_root)"/hooks/config/*.json; do
    [ -e "$f" ] || continue
    case "$f" in
    *.py) printf '%s\n' "$GM_YAML" | cat - "$f" | gemit "hooks/${f#*/hooks/}" ;;
    *) cat <"$f" | gemit "hooks/${f#*/hooks/}" ;;
    esac
  done
}

# --- the install contract ---------------------------------------------------

# Caveat: the counts are read from the tree at generation time, so the committed
# README is only right while the tree is unchanged; `--check` is what proves it.
greadme() {
  local root agents cmds skills rules stage
  root="$(claude_root)"
  agents="$(find "$root/agents" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  cmds="$(find "$root/commands" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  skills="$(find "$root/skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
  rules="$(grule_names | wc -l | tr -d ' ')"
  stage="$(grep -l 'stage: rule' "$root"/skills/*/SKILL.md | wc -l | tr -d ' ')"
  {
    printf '%s\n\n' "$GM_MD"
    cat "$root/tools/lib/gemini-README.md"
    printf '\n---\n\nGenerated from: %s agents, %s commands, %s skills, %s always-on rules, %s path-scoped rule skills.\n' \
      "$agents" "$cmds" "$skills" "$rules" "$stage"
  } | gemit "README.md"
}
