#!/usr/bin/env bash
# export-copilot.sh — the GitHub Copilot CLI dialect, generated from the Claude sources.
#
# Sourced by tools/export.sh, never executed. One function per output file, each
# writing to $XOUT. The canonical sources stay agents/, commands/, skills/ and
# rules/; nothing here edits them.
#
# Every claim this file makes was measured on Copilot CLI 1.0.89 on 2026-09-30.
# The commands, the footnotes and the negative controls are in
# doc/HARNESSES.md, section "copilot, measured for X2". Read that before changing
# a line here, because most of what follows is a surprise.
#
# What is generated, and why so little:
#   plugin.json            Agent Plugins 1.0 at the root, version copied from the
#                          kit's own manifest so there is one version source.
#   commands/<n>.md        the Claude sources are NOT valid YAML: a `description:`
#                          plain scalar holding "Usage: /devil:x" is a mapping
#                          value, and copilot's parser rejects it outright. 10 of
#                          the kit's 18 commands fail to load unfixed.
#   hooks.json             copilot reads the hook `command` as a shell line and
#                          ignores `args`, so a `command: python3` + `args: [path]`
#                          hook runs python3 with the event JSON as its program and
#                          dies on a NameError. The line is collapsed instead.
#   copilot-instructions.md  always-on rules. A plugin CANNOT ship these: the CLI
#                          reads none of AGENTS.md, CLAUDE.md,
#                          .github/copilot-instructions.md or
#                          .github/instructions/ from a plugin root. The host has
#                          to copy this file, so it is generated here.
#
# What is NOT generated, because copilot reads the Claude layout as it is:
#   skills/ and agents/    symlinked by the install, never copied. Measured: a
#                          symlinked `skills/` listed 23 plugin skills and a
#                          symlinked `agents/` registered 11 namespaced agents.
#   *.instructions.md      generated on purpose NOT. `applyTo:` is not a lazy-load
#                          gate here: every instruction file is listed in the
#                          prompt whatever its pattern, and a pattern narrower than
#                          `**` only earns a pointer row the model must read.

# --- primitives -------------------------------------------------------------

# Same three-line rule as the opencode exporter: a frontmatter file cannot open
# with its notice, because line 1 has to be the `---` fence or the block reads as
# body text and every field is lost. Markdown and JSON carry the notice on line 1
# (`<!-- -->`) and in a `_comment` key respectively; the command files carry it on
# line 2 as a YAML comment.
XCP_MD="<!-- GENERATED by 'devil export copilot' from the kit's Claude-format sources. Do not edit; run 'devil export copilot' instead. -->"
XCP_YAML="# GENERATED by 'devil export copilot' from the kit's Claude-format sources. Do not edit; run 'devil export copilot' instead."
XCP_YAML_JSON="GENERATED by 'devil export copilot'. Do not edit; run 'devil export copilot' instead."

xcp_emit() {
  mkdir -p "$(dirname "$XOUT/$1")"
  cat >"$XOUT/$1"
}

xcp_manifest_version() {
  # One version source: the kit's own plugin manifest. A bump there without
  # re-running the export is drift, and `export.sh --check copilot` fails on it.
  fm_json_field "$(claude_root)/.claude-plugin/plugin.json" version
}

# A JSON string field of a flat manifest. Deliberately not a JSON parser: this
# file is generated and its inputs are ours, so a dependency is not warranted.
# Caveat: reads a scalar on one line. A value written with a flow map, an escape
# or a line break is missed and the field is emitted empty, which the test for a
# non-empty version catches.
fm_json_field() {
  sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$1" | head -1
}

# --- manifest ---------------------------------------------------------------

xcp_plugin_json() {
  local version
  version="$(xcp_manifest_version)"
  # The notice rides in `_comment` because JSON has no comment form, the same
  # convention hooks/config/hooks-config.json already uses.
  cat <<JSON | xcp_emit "plugin.json"
{
  "_comment": "$XCP_YAML_JSON skills/ and agents/ are symlinks to the kit, not copies; see README.md.",
  "name": "devil",
  "version": "$version",
  "description": "Quality kit for Claude Code: spec, risk verdict, test-first build, strict gate."
}
JSON
}

# --- commands ---------------------------------------------------------------

xcp_body() { awk 'NR == 1 && $0 == "---" { inside = 1; next } inside && $0 == "---" { body = 1; next } body' "$1"; }

# Copilot advertises a command by its bare name, with no `/plugin:` namespace, so
# a description naming `/devil:x` names something the user cannot type.
xcp_command() {
  local f="$1" name desc
  name="$(fm_field "$f" name)"
  [ -n "$name" ] || name="$(basename "$f" .md)"
  desc="$(fm_desc "$f" | sed -E "s#/devil:$name\b#/$name#g")"
  {
    echo "---"
    echo "$XCP_YAML"
    # A folded block, not the source's plain scalar. A plain scalar cannot hold
    # ": " and the kit's descriptions do, so the source form is invalid YAML
    # and copilot drops the command with a parse error naming the line.
    printf 'description: >\n'
    printf '%s\n' "$desc" | fold -s -w 88 | sed 's/[[:space:]]*$//; s/^/  /'
    echo "---"
  } | xcp_emit "commands/$name.md"
  xcp_body "$f" >>"$XOUT/commands/$name.md"
}

xcp_commands() {
  local f
  for f in "$(claude_root)"/commands/*.md; do
    [ -e "$f" ] || continue
    xcp_command "$f"
  done
}

# --- hooks ------------------------------------------------------------------

# One `command` string per hook, and the keys copilot does not read dropped.
# Kept as a transformation of the kit's own hooks.json so a new event there
# needs no change here: the day it is added, it is generated too.
# Caveat: a hook whose `command` is already a full line gets that line twice
# when it also has `args`, which is the shape Claude uses and the one this
# collapses. Read the output if you add such a hook.
xcp_hooks() {
  python3 - "$(claude_root)/hooks/hooks.json" "$XCP_YAML_JSON" <<'PY'
import json, sys
src, notice = sys.argv[1], sys.argv[2]


def dquote(word):
    """One shell word, double-quoted.

    Not shlex.quote: that single-quotes, and a single-quoted ${CLAUDE_PLUGIN_ROOT}
    is a literal the shell will not expand, which is the whole point of the line.
    Double quotes still expand $VAR and still split on nothing, which is what a
    kit path with a space needs (measured: unquoted exit 127, quoted argc=1).
    Only " and \\ and ` are escaped; $ is left alone on purpose.
    """
    out = word.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
    return '"' + out + '"'


data = json.load(open(src))
out = {"_comment": notice, "hooks": {}}
for event, groups in data["hooks"].items():
    new = []
    for group in groups:
        g = {k: v for k, v in group.items() if k != "hooks"}
        hooks = []
        for h in group["hooks"]:
            line = " ".join(dquote(p) for p in [h["command"], *h.get("args", [])])
            new_h = {"type": "command", "command": line}
            if "timeout" in h:
                new_h["timeout"] = h["timeout"]
            hooks.append(new_h)
        g["hooks"] = hooks
        new.append(g)
    out["hooks"][event] = new
print(json.dumps(out, indent=2))
PY
}

xcp_hooks_file() { xcp_hooks | xcp_emit "hooks.json"; }

# --- always-on rules --------------------------------------------------------

# A plugin cannot ship instructions (measured: four candidate files at a plugin
# root, all invisible to `copilot instruction list`), so the rules travel as a
# file the host copies to .github/copilot-instructions.md.
xcp_instructions() {
  local f
  {
    echo "$XCP_MD"
    echo
    echo "# Always-on rules, for Copilot CLI"
    echo
    echo "Copy this file to \`<host>/.github/copilot-instructions.md\`. Generated by"
    echo "\`devil export copilot\` from the kit's \`rules/\`; never edit it here."
    echo
    for f in "$(claude_root)"/rules/*.md; do
      [ -e "$f" ] || continue
      cat "$f"
      echo
    done
  } | xcp_emit "copilot-instructions.md"
}

# --- the install contract ---------------------------------------------------

xcp_readme() {
  local root agents cmds
  root="$(claude_root)"
  agents="$(find "$root/agents" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  cmds="$(find "$root/commands" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  {
    printf '%s\n\n' "$XCP_MD"
    cat "$root/tools/lib/copilot-README.md"
    printf '\n---\n\nGenerated from: %s agents and %s commands. The skills and the agents are\nsymlinked, not copied.\n' \
      "$agents" "$cmds"
  } | xcp_emit "README.md"
}
