#!/usr/bin/env bash
# export-opencode.sh — the OpenCode 2.x dialect, generated from the Claude sources.
#
# Sourced by tools/export.sh, never executed. One function per output file, each
# writing to $XOUT. The canonical sources stay agents/, commands/, skills/ and
# rules/; nothing here edits them.
#
# What is generated and why:
#   agents/<n>.md     V2 agent frontmatter: mode, and a permissions list where a
#                     Claude `tools:` list becomes V2 allow rules over a deny-all
#                     base, so an ungranted capability is denied, never assumed.
#   commands/<n>.md   description + body, $ARGUMENTS kept, Claude-only frontmatter
#                     dropped, and /devil:<name> rewritten to the /<name> OpenCode
#                     actually registers.
#   plugins/devil.js  the hook bridge, copied from tools/lib/opencode-plugin.js.
#   opencode.json     the one config key a host must add (skills paths).
#   README.md         the install contract and the honest capability table.
#
# No AGENTS.md is generated. V2 reads AGENTS.md and nothing else, but the bridge
# already injects the same rules as system text (measured), so a generated copy
# would be a second copy of the same 27 KB that a host might load on top of the
# injection. The README documents the file route for a host that cannot load a
# plugin instead of shipping the file.

# --- primitives -------------------------------------------------------------

# Every generated file opens with a line its own format can carry as a comment:
# `<!-- -->` for prose markdown, `#` inside a YAML frontmatter block, `//` for JS.
# A frontmatter file cannot START with the comment: line 1 has to be the `---`
# fence or the block is read as body text and every field is silently lost.
XH_MD="<!-- GENERATED by 'devil export opencode' from the kit's Claude-format sources. Do not edit; run 'devil export opencode' instead. -->"
XH_YAML="# GENERATED by 'devil export opencode' from the kit's Claude-format sources. Do not edit; run 'devil export opencode' instead."
XH_JS="// GENERATED by 'devil export opencode' from the kit's Claude-format sources. Do not edit; run 'devil export opencode' instead."

xemit() {
  mkdir -p "$(dirname "$XOUT/$1")"
  cat >"$XOUT/$1"
}

xrule_names() { find "$(claude_root)/rules" -maxdepth 1 -name '*.md' -printf '%f\n' | sort; }

# --- agents -----------------------------------------------------------------

# A Claude `tools:` value is a comma list, or a YAML block list. Both are read
# here; anything else reads as absent, which makes the agent read-only rather
# than over-privileged: the failure direction is the safe one.
# Caveat: line-oriented. A flow list (`tools: [Read, Bash]`) is not parsed and
# yields no grants, and a name that no V2 action exists for is dropped, so the
# deny-all base rule denies it.
xclaude_tools() {
  fm_block "$1" | awk '
    /^tools:[[:space:]]*\[/ { gsub(/^\[|\].*$/, ""); print; exit }
    /^tools:[[:space:]]*[^[:space:]]/ {
      sub(/^tools:[[:space:]]*/, "")
      gsub(/[\[\]]/, "")
      print
      exit
    }
    /^tools:[[:space:]]*$/ { inside = 1; next }
    inside && /^[[:space:]]*-[[:space:]]+/ { sub(/^[[:space:]]*-[[:space:]]*/, ""); print; next }
    inside { exit }
  ' | tr ',' '\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v '^$'
}

# Claude tool name -> the V2 permission action that governs it. V2 has no
# `bash` action: a shell command is `shell`, which is also the tool name the
# hook bridge sees (measured 2026-09-30).
xv2_action() {
  case "$1" in
  Read) echo read ;;
  Grep) echo grep ;;
  Glob | LS) echo glob ;;
  Edit | Write | MultiEdit | NotebookEdit | Patch) echo edit ;;
  Bash | BashOutput | KillShell) echo shell ;;
  WebFetch) echo webfetch ;;
  WebSearch) echo websearch ;;
  Task | Agent) echo subagent ;;
  Skill) echo skill ;;
  *) echo "" ;;
  esac
}

xagent_body() { awk 'NR == 1 && $0 == "---" { inside = 1; next } inside && $0 == "---" { body = 1; next } body' "$1"; }

xoc_agent() {
  local f="$1" name desc action
  name="$(fm_field "$f" name)"
  desc="$(fm_desc "$f")"
  {
    echo "---"
    echo "$XH_YAML"
    echo "description: >"
    # Folded so a multi-line Claude description survives as valid YAML. A line
    # with trailing whitespace would end the block, so it is stripped.
    printf '%s\n' "$desc" | fold -s -w 88 | sed 's/[[:space:]]*$//; s/^/  /'
    echo "mode: subagent"
    echo "permissions:"
    # Deny-all first: V2 takes the last matching rule, so every grant below is an
    # exception to it and anything not granted stays denied.
    echo '  - action: "*"'
    echo '    resource: "*"'
    echo "    effect: deny"
    while read -r tool; do
      action="$(xv2_action "$tool")"
      [ -n "$action" ] || continue
      echo "  - action: $action"
      echo '    resource: "*"'
      echo "    effect: allow"
    done < <(xclaude_tools "$f" | sort -u)
    # The closing fence. Without it the block never terminates, the host reads the
    # body as frontmatter, `mode:` is lost, and every agent comes back a primary
    # agent that no subagent tool can launch. Measured on 2.0.18.
    echo "---"
  } | xemit "agents/$name.md"
  # The body is appended as it is: xagent_body already ends every line with a
  # newline, and one more is what left a double blank line at the end of the file.
  xagent_body "$f" >>"$XOUT/agents/$name.md"
}

xoc_agents() {
  local f
  for f in "$(claude_root)"/agents/*.md; do
    [ -e "$f" ] || continue
    xoc_agent "$f"
  done
}

# --- commands ---------------------------------------------------------------

# The description names the invocation, and Claude namespaces it `/devil:<name>`
# because a plugin must not shadow a user command. OpenCode registers `/<name>`,
# so keeping the namespace would print a name that does not exist.
xoc_command() {
  local f="$1" name desc
  name="$(fm_field "$f" name)"
  [ -n "$name" ] || name="$(basename "$f" .md)"
  desc="$(fm_desc "$f" | sed -E "s#/devil:$name\b#/$name#g")"
  {
    echo "---"
    echo "$XH_YAML"
    printf 'description: >\n'
    printf '%s\n' "$desc" | fold -s -w 88 | sed 's/[[:space:]]*$//; s/^/  /'
    echo "---"
  } | xemit "commands/$name.md"
  xagent_body "$f" >>"$XOUT/commands/$name.md"
}

xoc_commands() {
  local f
  for f in "$(claude_root)"/commands/*.md; do
    [ -e "$f" ] || continue
    xoc_command "$f"
  done
}

# --- the hook bridge, the rules, the config, the contract --------------------

xoc_plugin() {
  {
    echo "$XH_JS"
    cat "$(claude_root)/tools/lib/opencode-plugin.js"
  } | xemit "plugins/devil.js"
}

xoc_config() {
  # One key. The plugin path is NOT here on purpose: 2.0.18 ignores a local path
  # in `plugins` (measured), so the bridge is symlinked into .opencode/plugins/.
  # JSON has no comment form, so the generated notice rides in a `_comment` key,
  # the same convention hooks/config/hooks-config.json already uses.
  cat <<'JSON' | xemit "opencode.json"
{
  "$schema": "https://opencode.ai/config.json",
  "_comment": "GENERATED by 'devil export opencode'. Do not edit. Merge 'skills' into the host's own opencode.json; @KIT_ROOT@ is the absolute path of the kit checkout.",
  "skills": ["@KIT_ROOT@/skills"]
}
JSON
}

# The install contract. This file is the interface between this slice and the
# setup slice, and between this slice and a peer wiring graph_render, so it
# states exact paths, exact keys and the measured limits rather than a summary.
# Caveat: the counts are read from the tree at generation time, so the committed
# README is only right while the tree is unchanged; `--check` is what proves it.
xoc_readme() {
  local root agents cmds skills rules stage
  root="$(claude_root)"
  agents="$(find "$root/agents" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  cmds="$(find "$root/commands" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  skills="$(find "$root/skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
  rules="$(xrule_names | wc -l | tr -d ' ')"
  stage="$(grep -l 'stage: rule' "$root"/skills/*/SKILL.md | wc -l | tr -d ' ')"
  {
    printf '%s\n\n' "$XH_MD"
    cat "$root/tools/lib/opencode-README.md"
    printf '\n---\n\nGenerated from: %s agents, %s commands, %s skills, %s always-on rules, %s path-scoped rule skills.\n' \
      "$agents" "$cmds" "$skills" "$rules" "$stage"
  } | xemit "README.md"
}
