#!/usr/bin/env bash
# export-codex.sh — the Codex CLI dialect, generated from the Claude sources.
#
# Sourced by tools/export.sh, never executed. One function per output file, each
# writing to $XOUT. The canonical sources stay agents/, commands/, skills/ and
# rules/; nothing here edits them.
#
# What is generated, and why so little:
#   plugin.json        portable Agent Plugins 1.0 manifest, built by codex-manifest.py
#                      from .claude-plugin/plugin.json. The version is copied, never
#                      written here, so plugin.json stays the one version source.
#   hooks/hooks.json   the kit's hooks/hooks.json reduced to the twelve events Codex
#                      fires, by codex-hooks.py.
#   AGENTS.md          the twelve always-on rules as the one file a host drops in a
#                      project root, which is the only place Codex reads them.
#   README.md          the install contract and the honest capability table.
#
# What is NOT generated: skills, agents, commands. Codex reads a plugin's `skills/`
# natively and advertises each as `devil:<name>` (measured, doc/HARNESSES.md "codex,
# measured for X4"), and it rewrites `commands/*.md` into
# `.codex-plugin/migrated-command-skills/` by itself. Copying them here would be a
# second copy of files the harness already reads, and would drift.

# --- primitives -------------------------------------------------------------

# The portable manifest has no place for a comment: its schema forbids unknown
# keys, so plugin.json carries no in-file notice and the export's test asserts the
# key set instead. Markdown and the hooks `description` can carry one.
CXH_MD="<!-- GENERATED by 'devil export codex' from the kit's Claude-format sources. Do not edit; run 'devil export codex' instead. -->"
CXH_NOTE="GENERATED by 'devil export codex' from the kit's Claude-format sources. Do not edit; run 'devil export codex' instead."

cxemit() {
  mkdir -p "$(dirname "$XOUT/$1")"
  cat >"$XOUT/$1"
}

cxrule_names() { find "$(claude_root)/rules" -maxdepth 1 -name '*.md' -printf '%f\n' | sort; }

# python3 is not optional here: the two transforms parse their source rather than
# pattern-match it, because a pattern that misses a field writes a manifest that
# installs wrong instead of failing. Without it the export must fail loudly.
# Caveat: the traceback is suppressed and replaced by one line naming the output
# that did not land, so a failure names a file rather than a stack frame.
cxpython() {
  local script="$1"
  shift
  have python3 || {
    echo "export codex: python3 is required to generate the manifests" >&2
    return 2
  }
  mkdir -p "$(dirname "$2")"
  python3 "$(claude_root)/tools/lib/$script" "$@" 2>/dev/null || {
    echo "export codex: could not write $2" >&2
    return 2
  }
}

# --- the manifest and the hooks ----------------------------------------------

cx_manifest() { cxpython codex-manifest.py "$(claude_root)/.claude-plugin/plugin.json" "$XOUT/plugin.json"; }

cx_hooks() { cxpython codex-hooks.py "$(claude_root)/hooks/hooks.json" "$XOUT/hooks/hooks.json" "$CXH_NOTE"; }

# --- the always-on rules -----------------------------------------------------

# Codex reads `AGENTS.md` from the project tree, not from an installed plugin
# (measured: a plugin-root AGENTS.md never reached the prompt, a project one did),
# so this file is a file a host links or copies into the project root.
cx_agents_md() {
  local root f
  root="$(claude_root)"
  {
    printf '%s\n\n' "$CXH_MD"
    printf '# Always-on rules\n\n'
    printf 'The kit on Codex CLI: the rules below are the whole of it. Every one is the\n'
    printf 'verbatim body of a file under `rules/` in the kit checkout, so a rule edited\n'
    printf 'there is edited here after `devil export codex`.\n'
    for f in $(cxrule_names); do
      printf '\n---\n\n'
      cat "$root/rules/$f"
    done
  } | cxemit "AGENTS.md"
}

# --- the install contract ----------------------------------------------------

# Caveat: the counts come from the tree at generation time, so the committed
# README is only right while the tree is unchanged; `--check` is what proves it.
cx_readme() {
  local root rules skills cmds
  root="$(claude_root)"
  rules="$(cxrule_names | wc -l | tr -d ' ')"
  skills="$(find "$root/skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
  cmds="$(find "$root/commands" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
  {
    printf '%s\n\n' "$CXH_MD"
    cat "$root/tools/lib/codex-README.md"
    printf '\n---\n\nGenerated from: %s skills, %s always-on rules, %s commands.\n' \
      "$skills" "$rules" "$cmds"
  } | cxemit "README.md"
}
