#!/usr/bin/env bash
# test_export_copilot.sh — the copilot export must be reproducible, loadable,
# and honest about what it does not do.
#
# A generator is only worth having if drift is loud, so the negative controls are
# the point: a hand-edited generated file must FAIL --check, an unknown harness must
# exit 2, a description that is a plain scalar (the shape the kit's own sources use,
# and the one copilot's parser rejects) must come out as a block, and a hook in the
# Claude shape, which would run the wrong program, must not survive. A test that only
# proves the happy path would pass just as well with a broken generator.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASS=0
FAIL=0
SKIP=0

ok() {
  echo "ok   - $1"
  PASS=$((PASS + 1))
}
no() {
  echo "FAIL - $1"
  FAIL=$((FAIL + 1))
}
skip() {
  echo "skip - $1"
  SKIP=$((SKIP + 1))
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
# A throwaway COPILOT_HOME: these checks must never write to the real ~/.copilot,
# where a session left behind is a credential on disk.
export COPILOT_HOME="$TMP/copilot-home"
mkdir -p "$COPILOT_HOME"

# --- 1. the committed tree is what the sources generate ------------------------
if out="$(cd "$ROOT" && bash tools/export.sh --check copilot 2>&1)"; then
  ok "committed dist/copilot matches its sources"
else
  no "committed dist/copilot is stale: $out"
fi

# A hand edit to a generated file is drift. Proved by making one.
DRIFT="$ROOT/dist/copilot/commands/deal.md"
cp "$DRIFT" "$TMP/keep"
printf '\nhand edit\n' >>"$DRIFT"
if (cd "$ROOT" && bash tools/export.sh --check copilot >/dev/null 2>&1); then
  no "a hand-edited generated file must fail --check"
else
  ok "a hand-edited generated file fails --check"
fi
cp "$TMP/keep" "$DRIFT"
if (cd "$ROOT" && bash tools/export.sh --check copilot >/dev/null 2>&1); then
  ok "restoring the file clears the drift"
else
  no "restore must put the tree back in sync"
fi
# An unknown harness is exit 2, never a silent pass.
(cd "$ROOT" && bash tools/export.sh --check nosuch >/dev/null 2>&1)
[ $? -eq 2 ] && ok "unknown harness exits 2" || no "unknown harness must exit 2"

# The opencode target must be untouched by this slice.
if (cd "$ROOT" && bash tools/export.sh --check opencode >/dev/null 2>&1); then
  ok "dist/opencode still matches its sources"
else
  no "the copilot export must not disturb dist/opencode"
fi
# --- 2. the manifests are valid JSON, and carry the one version ---------------
# A missing or empty version is the failure a version source has: the dist would
# claim a version of its own and auto-update would never fire.
for m in plugin.json hooks.json; do
  if python3 -c "import json;json.load(open('$ROOT/dist/copilot/$m'))" 2>/dev/null; then
    ok "$m is valid JSON"
  else
    no "$m is not valid JSON"
  fi
done
want="$(python3 -c "import json;print(json.load(open('$ROOT/.claude-plugin/plugin.json'))['version'])" 2>/dev/null)"
got="$(python3 -c "import json;print(json.load(open('$ROOT/dist/copilot/plugin.json'))['version'])" 2>/dev/null)"
[ -n "$got" ] && [ "$want" = "$got" ] &&
  ok "the dist version is copied from .claude-plugin/plugin.json ($got)" ||
  no "version drift: plugin.json says '$want', the dist says '$got'"

# copilot ignores `args`, so a hook still carrying one runs the wrong program:
# `command: python3` with the path in `args` invokes python3 with the event JSON
# as its program.
if python3 -c "
import json
for event, groups in json.load(open('$ROOT/dist/copilot/hooks.json'))['hooks'].items():
    for g in groups:
        for h in g['hooks']:
            assert 'args' not in h, event + ' still carries args'
            assert h['type'] == 'command', event
" 2>/dev/null; then
  ok "no generated hook carries an args array"
else
  no "a generated hook still carries args, so copilot would run the wrong program"
fi

# --- 3. every generated file declares itself generated, and its frontmatter ---
# A frontmatter file cannot open with its notice: line 1 has to be the `---` fence
# or the block reads as body text and every field is lost. So the commands carry it
# on line 2 as a YAML comment, markdown on line 1, JSON in a `_comment` key.
missing=""
while read -r f; do
  head -3 "$f" | grep -q 'GENERATED by' || missing="$missing $f"
done < <(find "$ROOT/dist/copilot" -type f)
[ -z "$missing" ] && ok "all $(find "$ROOT/dist/copilot" -type f | wc -l | tr -d ' ') generated files carry the header" ||
  no "no generated header on:$missing"

# Two questions, one interpreter. (a) does every generated command frontmatter
# parse as a closed YAML mapping with a description: copilot drops a file whose
# frontmatter does not parse, naming the line, and says nothing else. (b) the
# control for (a): the kit's own `description:` plain scalar holding "Usage: /x" is
# a mapping value and MUST be rejected, or (a) measures nothing.
if python3 -c 'import yaml' 2>/dev/null; then
  res="$(
    python3 - "$ROOT/dist/copilot" <<'PY'
import glob, sys, yaml
bad = []
for f in sorted(glob.glob(sys.argv[1] + "/commands/*.md")):
    parts = open(f).read().split("---\n")
    if len(parts) < 3:
        bad.append(f + " (frontmatter never closes)")
    else:
        try:
            d = yaml.safe_load(parts[1])
        except Exception as exc:
            bad.append(f + " (" + str(exc).splitlines()[0] + ")")
        else:
            if not isinstance(d, dict) or "description" not in d:
                bad.append(f + " (no description)")
try:
    yaml.safe_load("description: Run it. Usage: /x [a|b]")
    print("CONTROL-ACCEPTED")
except yaml.YAMLError:
    print("CONTROL-REJECTED")
print("\n".join(bad))
PY
  )"
  case "$res" in
  *CONTROL-REJECTED*) ok "a plain scalar holding ': ' is rejected, so the fold is a real fix" ;;
  *) no "the plain-scalar control parsed, so the frontmatter check proves nothing" ;;
  esac
  badfm="$(printf '%s\n' "$res" | grep -v '^CONTROL-')"
  [ -z "$badfm" ] && ok "every generated command frontmatter is a closed YAML mapping with a description" ||
    no "command frontmatter not usable by copilot:"$'\n'"$badfm"
else
  skip "python3 with PyYAML unavailable: frontmatter not parsed as YAML"
fi

# The description must come out as a block, never the source's plain scalar, and
# named the way copilot advertises it: a plugin command is bare-named, so
# `/devil:bench` names nothing the user can type.
B="$ROOT/dist/copilot/commands/bench.md"
if grep -q '^description: >$' "$B" && grep -q 'Usage: /bench ' "$B"; then
  ok "a description with ': ' is folded, and /devil:bench is rewritten to /bench"
else
  no "the description is still the plain scalar copilot rejects, or names the Claude namespace"
fi
grep -q '\$ARGUMENTS' "$B" &&
  ok "\$ARGUMENTS survives the export" || no "\$ARGUMENTS was lost"

# --- 4. a fixture kit: a new command exports, a bad one would not survive -----
FIX="$TMP/kit"
mkdir -p "$FIX"/{commands,skills/sample,rules,hooks/scripts,tools/lib,.claude-plugin}
cp "$ROOT/tools/export.sh" "$FIX/tools/"
cp "$ROOT/tools/lib/common.sh" "$ROOT/tools/lib/export-copilot.sh" "$FIX/tools/lib/"
cp "$ROOT/tools/lib/copilot-README.md" "$FIX/tools/lib/"
printf '%s\n' '{ "name": "fixkit", "version": "9.9.9" }' >"$FIX/.claude-plugin/plugin.json"
printf -- '---\nname: fixrule\n---\n\nA rule.\n' >"$FIX/rules/fixrule.md"
printf -- '---\nname: sample\ndescription: a sample skill\n---\n\nBody\n' >"$FIX/skills/sample/SKILL.md"
# The two shapes the kit itself uses and copilot rejects: a plain scalar holding
# "Usage:", and a hook with `command` plus `args`.
printf -- '---\ndescription: Do the thing. Usage: /devil:thing <arg>\nmetadata:\n  kind: command\n---\n\nDo $ARGUMENTS now.\n' \
  >"$FIX/commands/thing.md"
printf '%s\n' '{"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"python3","args":["${CLAUDE_PLUGIN_ROOT}/hooks/scripts/hooks.py"],"timeout":5}]}]}}' \
  >"$FIX/hooks/hooks.json"

if (cd "$FIX" && bash tools/export.sh copilot >/dev/null 2>&1) &&
  [ -f "$FIX/dist/copilot/commands/thing.md" ]; then
  ok "a fixture kit exports, and a new command appears in the output"
else
  no "the fixture kit must export, with commands/thing.md in the output"
fi

# The fixture's manifest version, not the kit's: one version source, copied.
fv="$(python3 -c "import json;print(json.load(open('$FIX/dist/copilot/plugin.json'))['version'])" 2>/dev/null)"
[ "$fv" = "9.9.9" ] && ok "the fixture version is copied from the fixture manifest ($fv)" ||
  no "the fixture version is '$fv', expected 9.9.9"

# Asserted by reading values, never by grepping the file: a grep for `args` also
# matches the word in a notice, and a grep for the path cannot tell one argument
# from two. The single-quote assertion is the other half: `'${CLAUDE_PLUGIN_ROOT}'`
# is a literal no shell expands, and the hook then cannot find the kit.
if python3 -c "
import json
h = json.load(open('$FIX/dist/copilot/hooks.json'))['hooks']['PreToolUse'][0]['hooks'][0]
assert 'args' not in h, h
assert h['command'] == '\"python3\" \"\${CLAUDE_PLUGIN_ROOT}/hooks/scripts/hooks.py\"', h['command']
assert chr(39) not in h['command'], 'single-quoted, so the shell would not expand it'
" 2>/dev/null; then
  ok "a Claude command+args hook collapses into one quoted, still-expandable line"
else
  no "the hook was not collapsed, or was quoted so the shell cannot expand it"
fi

# The fixture command must survive a real parse, which is the whole reason the
# generator folds the description.
if python3 -c 'import yaml' 2>/dev/null; then
  if python3 -c "
import yaml
d = yaml.safe_load(open('$FIX/dist/copilot/commands/thing.md').read().split('---\n')[1])
assert isinstance(d, dict) and '/thing' in d['description'], d
" 2>/dev/null; then
    ok "the fixture command frontmatter parses and the namespace is rewritten"
  else
    no "the fixture command frontmatter is unusable"
  fi
else
  skip "PyYAML unavailable: the fixture description was not parsed"
fi

# --- 5. the dist, loaded by the real CLI --------------------------------------
# The install is reproduced here rather than committed: a symlink into a checkout
# is a path that only means something on the machine that made it, and --check
# would read it as drift. Staging is the dist plus the three symlinks the README
# tells a user to create.
PLUG="$TMP/plugin"
HOSTD="$TMP/host"
mkdir -p "$HOSTD/.github" "$PLUG"
cp -r "$ROOT/dist/copilot/." "$PLUG/"
ln -sfn "$ROOT/skills" "$PLUG/skills"
ln -sfn "$ROOT/agents" "$PLUG/agents"
ln -sfn "$ROOT/hooks" "$PLUG/hooks"
cp "$ROOT/dist/copilot/copilot-instructions.md" "$HOSTD/.github/copilot-instructions.md"

if ! command -v copilot >/dev/null 2>&1; then
  # A check that could not run is a skip, never a pass. The deny path is the claim
  # the kit exists to make, so its skip is reported rather than folded away.
  skip "the copilot CLI is not installed: loading, parsing, agents and the deny path were not run"
else
  # Every CLI answer is captured before it is matched. `cmd | grep -q` closes the
  # pipe on the first match, copilot takes SIGPIPE, and under `pipefail` the
  # pipeline reports the SIGPIPE instead of the answer: a green result reads red.
  cli() { (cd "$HOSTD" && copilot "$@" 2>&1); }

  # The negative control comes first, deliberately: it is what makes every
  # "plugin" answer below mean the dist rather than the CLI's own built-ins.
  out="$(cli skill list --json)"
  if printf '%s' "$out" | grep -q '"source": "plugin"'; then
    no "plugin skills reported with no --plugin-dir: this check is not measuring the dist"
  else
    ok "without --plugin-dir the same host reports no plugin skills (negative control)"
  fi

  out="$(cli --plugin-dir "$PLUG" skill list --json)"
  if printf '%s' "$out" | grep -q '"source": "plugin"'; then
    ok "the CLI loads the kit skills through the dist"
  else
    no "the CLI loaded no plugin skills through the dist"
  fi

  # The parse failures the generator exists to remove: the kit's own sources
  # produce ten, the dist must produce none.
  n="$(cli --plugin-dir "$PLUG" skill list | grep -c 'failed to parse')"
  [ "$n" = "0" ] && ok "no command fails to parse through the dist" ||
    no "$n commands still fail to parse through the dist"
  out="$(cli --plugin-dir "$PLUG" --agent nosuch -p hi)"
  if printf '%s' "$out" | grep -q 'devil:reviewer'; then
    ok "the CLI registers the agents under the devil: namespace"
  else
    no "the CLI did not register the kit's namespaced agents: $out"
  fi
  out="$(cli --plugin-dir "$PLUG" instruction list)"
  if printf '%s' "$out" | grep -q 'copilot-instructions.md'; then
    ok "the host's copied instructions are found"
  else
    no "the copied copilot-instructions.md was not found: $out"
  fi

  FORCE='Run exactly this shell command and nothing else: git push --force origin main'
  DH="$TMP/denyhost"
  mkdir -p "$DH"
  # deny <plugin-args...> -> how many times the kit's own hook refused. The second
  # run is the control: with no plugin the same command must NOT be kit-refused, or
  # the first run proves nothing about the kit at all.
  deny() {
    (cd "$DH" && timeout 200 copilot "$@" --allow-all-tools -p "$FORCE" 2>&1) |
      grep -c 'Denied by preToolUse hook'
  }
  got="$(deny --plugin-dir "$PLUG")"
  [ "${got:-0}" -ge 1 ] && ok "the risk gate refuses a force-push through the dist" ||
    no "the force-push was not refused by the kit's hook; check the wording, copilot may have refused it"
  ctrl="$(deny)"
  [ "${ctrl:-0}" = "0" ] &&
    ok "the same force-push is not kit-refused with no plugin (negative control)" ||
    no "the negative control was also refused: the result above is not about the dist"
fi

echo
echo "$PASS passed, $FAIL failed, $SKIP skipped"
[ "$FAIL" -eq 0 ] || exit 1
