#!/usr/bin/env bash
# test_export_gemini.sh — the Gemini export must be reproducible, complete, honest.
#
# A generated extension nobody has run is a guess wearing a manifest, so the
# negative controls are the point: a hand-edited file must FAIL --check, an
# unmapped tool must NOT be denied, and the CLI's own validator must FAIL on a
# bad manifest for its pass on ours to mean anything.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASS=0
FAIL=0
SKIP=0
ok() {
  echo "ok   - $1"
  PASS=$((PASS + 1))
}
no() {
  echo "FAIL - $1"
  FAIL=$((FAIL + 1))
}
skip() {
  echo "skip - $1"
  SKIP=$((SKIP + 1))
}
# is <label> <got> <want>
is() { if [ "$2" = "$3" ]; then ok "$1"; else no "$1 (got '$2', want '$3')"; fi; }
# yes <label> <file> <pattern>    nope <label> <file> <pattern>
yes() { if grep -q -- "$3" "$2"; then ok "$1"; else no "$1"; fi; }
nope() { if grep -q -- "$3" "$2"; then no "$1"; else ok "$1"; fi; }
# fence <label> <file> <last line the notice may sit on>
fence() {
  [ "$(head -1 "$2")" = "---" ] && sed -n "2,$3p" "$2" | grep -q '^# GENERATED' && ok "$1" ||
    no "$1"
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
DIST="$ROOT/dist/gemini"

# --- 1. the committed tree is what the sources generate ------------------------
if out="$(cd "$ROOT" && bash tools/export.sh --check gemini 2>&1)"; then
  ok "committed dist/gemini matches its sources"
else
  no "committed dist/gemini is stale: $out"
fi

# A hand edit to a generated file is drift. Proved by making one.
cp "$DIST/commands/quality.toml" "$TMP/quality.keep"
printf '\nhand edit\n' >>"$DIST/commands/quality.toml"
(cd "$ROOT" && bash tools/export.sh --check gemini >/dev/null 2>&1) &&
  no "a hand-edited generated file must fail --check" ||
  ok "a hand-edited generated file fails --check"
cp "$TMP/quality.keep" "$DIST/commands/quality.toml"
(cd "$ROOT" && bash tools/export.sh --check gemini >/dev/null 2>&1) &&
  ok "restoring the file clears the drift" ||
  no "restore must put the tree back in sync"
(cd "$ROOT" && bash tools/export.sh --check nosuch >/dev/null 2>&1)
[ $? -eq 2 ] && ok "unknown harness exits 2" || no "unknown harness must exit 2"

# --- 2. the manifest ----------------------------------------------------------
# One version source: plugin.json carries it, the export reads it at write time.
jver() { sed -nE 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/p' "$1" | head -1; }
is "gemini-extension.json carries plugin.json's version" \
  "$(jver "$DIST/gemini-extension.json")" "$(jver "$ROOT/.claude-plugin/plugin.json")"

# In place, not `-i`: an interrupted run must not leave a .bak next to the
# manifest, and a stray file there is a dangling reference for selfcheck.
cp "$ROOT/.claude-plugin/plugin.json" "$TMP/plugin.orig"
sed -E 's/"version": "[^"]*"/"version": "9.9.9"/' "$TMP/plugin.orig" \
  >"$ROOT/.claude-plugin/plugin.json"
(cd "$ROOT" && bash tools/export.sh --check gemini >/dev/null 2>&1) && rc=0 || rc=$?
mv "$TMP/plugin.orig" "$ROOT/.claude-plugin/plugin.json"
[ "$rc" -ne 0 ] && ok "a plugin.json version bump fails --check until the export re-runs" ||
  no "a version bump with no re-export must fail --check"
yes "the extension name uses only characters the CLI accepts" \
  "$DIST/gemini-extension.json" '"name": "[A-Za-z0-9-]\+"'

# --- 3. every generated file in its own format --------------------------------
# The notice goes where the format allows: JSON has no comment form so it rides
# in a documented key on line 3, a frontmatter file keeps the --- fence on line 1
# and the notice inside the block, a byte copy is exempt by name.
bad=""
while read -r f; do
  [ "$f" = "$DIST/hooks/config/hooks-config.json" ] && continue
  head -3 "$f" | grep -q 'GENERATED by' || bad="$bad $f"
done < <(find "$DIST" -type f)
[ -z "$bad" ] && ok "every generated file but the one byte copy carries the header" ||
  no "no generated header on:$bad"

# One script reads every generated file with the parser its own format uses. The
# agent schema is `.strict()`, so an unknown key fails the file and does not warn.
cat >"$TMP/formats.py" <<'PY'
import glob, json, sys, yaml

root, allowed, bad = sys.argv[1], {"name", "description", "kind", "tools"}, []
why = lambda exc: str(exc).splitlines()[0]  # noqa: E731
for f in glob.glob(root + "/**/*.json", recursive=True):
    try:
        json.load(open(f))
    except Exception as exc:
        bad.append(f"{f} ({why(exc)})")
if sys.version_info >= (3, 11):
    import tomllib

    for f in glob.glob(root + "/commands/*.toml"):
        try:
            d = tomllib.load(open(f, "rb"))
        except Exception as exc:
            bad.append(f"{f} ({why(exc)})")
            continue
        if not d.get("prompt") or not d.get("description"):
            bad.append(f"{f} (no prompt or description)")
else:
    print("SKIP: no tomllib")
for f in sorted(glob.glob(root + "/agents/*.md")) + sorted(glob.glob(root + "/skills/*/SKILL.md")):
    parts = open(f).read().split("---\n")
    if len(parts) < 3:
        bad.append(f"{f} (frontmatter never closes)")
        continue
    try:
        d = yaml.safe_load(parts[1])
    except Exception as exc:
        bad.append(f"{f} ({why(exc)})")
        continue
    if not isinstance(d, dict) or not d.get("name") or not d.get("description"):
        bad.append(f"{f} (no name or description)")
    if "/agents/" in f and set(d) - allowed:
        bad.append(f"{f} (keys outside the strict schema: {sorted(set(d) - allowed)})")
    if "model" in d:
        bad.append(f"{f} (carries a model identifier)")
print("\n".join(x for x in bad if x))
PY
if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' 2>/dev/null; then
  badfm="$(python3 "$TMP/formats.py" "$DIST")"
  if printf '%s' "$badfm" | grep -q '^SKIP'; then
    skip "python3 is older than 3.11: no tomllib, the command TOML is not parsed"
    badfm="$(printf '%s' "$badfm" | grep -v '^SKIP')"
  else
    ok "every generated command TOML parsed with tomllib"
  fi
  [ -z "$badfm" ] && ok "every generated file parses in its own format, frontmatter closed" ||
    no "unusable generated file:"$'\n'"$badfm"
else
  skip "python3 with PyYAML unavailable: generated formats not parsed"
fi

# Line 1 of a frontmatter file has to stay the fence, or the loader reads the
# whole file as body text and every field is silently lost.
fence "an agent keeps the fence on line 1 and the notice on line 2" \
  "$DIST/agents/reviewer.md" 3
fence "a copied skill keeps the fence on line 1 and the notice in the block" \
  "$DIST/skills/debug/SKILL.md" 3

# --- 4. the hooks dialect -----------------------------------------------------
# Gemini's events, not Claude's: a Claude name here is a hook that never fires,
# and the file validates clean either way. A hook command is one shell string.
h="$DIST/hooks/hooks.json"
yes "hooks.json uses Gemini's event names" "$h" '"\(BeforeTool\|PreCompress\)"'
nope "hooks.json carries no Claude event name" "$h" '"\(PreToolUse\|PostToolUse\|PreCompact\)"'
yes "the hook command is one string naming the extension path" \
  "$h" '"command": "python3 ${extensionPath}/hooks/gemini-hook.py"'
nope "no Claude plugin root leaks into hooks.json" "$h" 'CLAUDE_PLUGIN_ROOT'
nope "no args array, which Gemini has no field for" "$h" '"args"'
# Gemini's timeout is milliseconds and the Claude manifest's is seconds, so the
# same number is a thousandfold off. A budget under 1000 ms is the symptom.
yes "hook timeouts are restated in milliseconds" "$h" '"timeout": 5000'
nope "no hook timeout small enough to be seconds read as ms" "$h" '"timeout": [0-9]"'
# The runtime has to travel with the manifest or the command names a script that
# is not there. The config is the one file with no notice, it being a byte copy.
[ -f "$DIST/hooks/scripts/hooks.py" ] && ok "the hook runtime is inside the extension" ||
  no "hooks/scripts/hooks.py is missing from the extension"
if diff "$DIST/hooks/config/hooks-config.json" "$ROOT/hooks/config/hooks-config.json" >/dev/null; then
  ok "hooks-config.json is a byte-for-byte copy, which is why it has no notice"
else
  no "hooks-config.json is not a byte-for-byte copy"
fi

# --- 5. the translator, on fixture payloads -----------------------------------
# hooks.py is the enforcement and this shim is all that is in front of it.
SHIM="$DIST/hooks/gemini-hook.py"
# env -u: a runner with DEVIL_AUTONOMY=1 (tests/test_autonomy.sh) would turn every ask silent.
shim() { printf '%s' "$1" | env -u DEVIL_AUTONOMY python3 "$SHIM" 2>/dev/null; }
dec() { shim "$1" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("decision",""))' 2>/dev/null; }
is "a force-push becomes a Gemini deny" \
  "$(dec '{"hook_event_name":"BeforeTool","tool_name":"run_shell_command","tool_input":{"command":"git push --force origin main"}}')" deny
is "an irreversible push becomes a Gemini ask" \
  "$(dec '{"hook_event_name":"BeforeTool","tool_name":"run_shell_command","tool_input":{"command":"git push origin main"}}')" ask
yes "a compaction note arrives as hookSpecificOutput.additionalContext" \
  <(shim '{"hook_event_name":"PreCompress"}') additionalContext
# Negative control: the tool name is load-bearing. A tool the map does not know
# is not a shell, so a dangerous string in it is not a dangerous command.
is "an unmapped tool is not denied, so the tool map is load-bearing" \
  "$(dec '{"hook_event_name":"BeforeTool","tool_name":"some_mcp_tool","tool_input":{"command":"git push --force origin main"}}')" ""
# Negative control: a pass-through shim would answer a name the CLI never sends.
is "a Claude-shaped payload produces no Gemini answer" \
  "$(dec '{"hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"git push --force origin main"}}')" ""
is "an unparseable payload produces no decision" "$(dec 'not json at all')" ""
is "an event with no handler produces no decision" "$(dec '{"hook_event_name":"Notification"}')" ""
# Gemini's write tool reports its path under one of four names; proved with
# .env, which risk.py will not let an agent write.
is "a path under any of the four keys becomes file_path" \
  "$(dec '{"hook_event_name":"BeforeTool","tool_name":"write_file","tool_input":{"path":"/tmp/probe/.env","content":"x"}}')" ask

# --- 6. a fixture kit: the mapping, on assets the kit does not have -------------
FIX="$TMP/kit"
mkdir -p "$FIX"/{agents,commands,skills/sample,rules,hooks/scripts,hooks/config,tools/lib} "$FIX/.claude-plugin"
cp "$ROOT/tools/export.sh" "$FIX/tools/"
cp "$ROOT/tools/lib/common.sh" "$ROOT/tools/lib/export-gemini.sh" \
  "$ROOT/tools/lib/gemini-hook.py" "$ROOT/tools/lib/gemini-README.md" "$FIX/tools/lib/"
cp "$ROOT/hooks/scripts/"*.py "$FIX/hooks/scripts/"
cp "$ROOT/hooks/config/hooks-config.json" "$FIX/hooks/config/"
printf '{"name":"devil","version":"7.7.7","description":"Fixture for Claude Code."}\n' \
  >"$FIX/.claude-plugin/plugin.json"
printf -- '---\nname: rules-x\n---\n\nA rule.\n' >"$FIX/rules/rules-x.md"
printf -- '---\nname: sample\ndescription: a sample skill\nallowed-tools: Read\n---\n\nBody\n' \
  >"$FIX/skills/sample/SKILL.md"
printf -- '---\ndescription: A look. Usage: /devil:look <target>\n---\n\nRead $ARGUMENTS closely.\n' \
  >"$FIX/commands/look.md"
printf -- '---\nname: looker\ndescription: Reads and reports, never edits.\nmodel: sonnet\nmemory: project\ntools: Read, Grep, Glob\n---\n\nLook only.\n' \
  >"$FIX/agents/looker.md"
# One Claude tool Gemini cannot name, and one agent with no tools line at all.
printf -- '---\nname: oddity\ndescription: Holds a tool Gemini has no name for.\ntools: TodoWrite\n---\n\nBody\n' \
  >"$FIX/agents/oddity.md"
printf -- '---\nname: blank\ndescription: No tools line whatsoever.\n---\n\nBody\n' \
  >"$FIX/agents/blank.md"

(cd "$FIX" && bash tools/export.sh gemini >/dev/null 2>&1) &&
  ok "a fixture kit exports" || no "the fixture kit must export"
F="$FIX/dist/gemini"
[ -f "$F/agents/looker.md" ] && ok "a new agent appears in the output" ||
  no "agents/looker.md missing from the fixture output"
[ -f "$F/commands/look.toml" ] && ok "a new command appears in the output" ||
  no "commands/look.toml missing from the fixture output"
is "the manifest takes the fixture's own version" "$(jver "$F/gemini-extension.json")" 7.7.7
yes "the manifest description names this harness, not Claude Code" \
  "$F/gemini-extension.json" '"description": "Fixture for Gemini CLI."'
yes "the command description is rewritten from /devil:look to /look" \
  "$F/commands/look.toml" 'Usage: /look <target>'
yes "\$ARGUMENTS becomes Gemini's {{args}} placeholder" \
  "$F/commands/look.toml" 'Read {{args}} closely'
a="$F/agents/looker.md"
nope "a generated agent kept no model identifier" "$a" 'model:'
nope "a generated agent kept no key the strict schema rejects" "$a" 'memory:'
nope "a read-only fixture granted no shell" "$a" '  - run_shell_command'
yes "a Claude tools list becomes Gemini tool names" "$a" '  - read_file'
# An unmapped Claude tool grants nothing, and so does an absent tools line: an
# omitted key inherits every tool, and an empty array is truthy in JS.
yes "an unmapped Claude tool becomes an empty list, not an inherited one" \
  "$F/agents/oddity.md" 'tools: \[\]'
yes "an agent with no tools line gets the explicit empty list" \
  "$F/agents/blank.md" 'tools: \[\]'
if diff <(sed '/^# GENERATED by /d' "$F/skills/sample/SKILL.md") \
  "$FIX/skills/sample/SKILL.md" >/dev/null; then
  ok "a copied skill is byte-identical to its source apart from the notice line"
  is "the notice sits on line 2, a YAML comment rather than a body H1" \
    "$(sed -n '2p' "$F/skills/sample/SKILL.md")" \
    "# GENERATED by 'devil export gemini' from the kit's Claude-format sources. Do not edit; run 'devil export gemini' instead."
else
  no "the skill copy is not verbatim"
fi
# Negative control for the drift gate: the fixture's dist is a second tree.
printf '\nhand edit\n' >>"$F/commands/look.toml"
(cd "$FIX" && bash tools/export.sh --check gemini >/dev/null 2>&1) &&
  no "a hand-edited file must fail the fixture's --check" ||
  ok "a hand-edited file fails the fixture's --check"

# --- 7. the CLI, if docker can install it --------------------------------------
# The container is the only place the harness exists here, and a skip is counted
# and printed rather than quietly counted as a pass.
# Caveat: the bound is a flat timeout, not a measurement. On a slow registry a
# first-time install can exceed it and the check SKIPs rather than failing.
if [ "${DEVIL_SKIP_GEMINI_CONTAINER:-0}" = 1 ]; then
  skip "DEVIL_SKIP_GEMINI_CONTAINER=1: gemini extensions validate not run"
elif ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
  skip "docker unavailable: gemini extensions validate not run"
else
  # gemini_validate <host dir> <extension path, inside the container>
  gemini_validate() {
    timeout 600 docker run --rm -v "$1:/t:ro" -w /t -e HOME=/tmp/h node:22-slim bash -lc \
      "npm i -g @google/gemini-cli >/dev/null 2>&1 && gemini extensions validate $2"
  }
  if out="$(gemini_validate "$ROOT" /t/dist/gemini 2>&1)"; then
    ok "gemini extensions validate accepted dist/gemini: $(printf '%s' "$out" | tail -1)"
  else
    no "gemini extensions validate rejected dist/gemini: $(printf '%s' "$out" | tail -3)"
  fi
  # The negative control: a validator that accepts this proves nothing above.
  mkdir -p "$TMP/badext"
  printf '{"name":"e_4","version":"1.0.0","description":"underscore name"}\n' \
    >"$TMP/badext/gemini-extension.json"
  if gemini_validate "$TMP" /t/badext >/dev/null 2>&1; then
    no "the validator accepted a manifest the CLI rejects, so it proves nothing"
  else
    ok "the validator rejects a bad name, so its pass above means something"
  fi
fi

echo
echo "$PASS passed, $FAIL failed, $SKIP skipped"
[ "$FAIL" -eq 0 ] || exit 1
